"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
export function MockSigningSession({ id }: { id: string }) {
  const [session, setSession] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch(`/api/rlusd/session/${id}`).then((r) => r.json()).then((j) => { if (j.error) setError(j.error); else setSession(j.session); }).catch((e) => setError(String(e))); }, [id]);
  async function run(action: string) { setBusy(true); try { const r = await fetch(`/api/rlusd/session/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error); setSession(j.session); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <div className="g-app"><main className="g-main" style={{ maxWidth: 560, margin: "0 auto", width: "100%" }}><div className="g-pill" style={{ display: "inline-block" }}>RLUSD V1</div><div className="g-sheet" style={{ marginTop: 16 }}><h1 className="g-display" style={{ fontSize: 30 }}>BUY 5 RLUSD</h1><p className="g-sub">Chain target 1440000 · quote RLUSD · user signs in production</p><p className="g-micro" style={{ marginTop: 8 }}>This preview does not connect a wallet, call Squid, or broadcast.</p>{session && <div style={{ marginTop: 20 }}><div className="g-kv"><span>Action</span><span>{String(session.action)}</span></div><div className="g-kv"><span>Source post</span><span>{String(session.xPostId)}</span></div><div className="g-kv"><span>Status</span><span>{String(session.status)}</span></div><div className="g-kv"><span>Referral</span><span>{String(session.referralCredit)} base units</span></div>{session.status !== "COMPLETE" && <button className="g-cta" onClick={() => void run("BUY")} disabled={busy}>{busy ? "Executing…" : "Execute destination BUY"}</button>}{session.status === "COMPLETE" && session.sellQuoteOut === undefined && <button className="g-cta" onClick={() => void run("SELL")} disabled={busy}>{busy ? "Selling…" : "SELL against actual reserve"}</button>}{session.sellQuoteOut !== undefined && <div className="g-alert good" style={{ marginTop: 12 }}>SELL settled: {String(session.sellQuoteOut)} RLUSD base units.</div>}</div>}{error && <div className="g-alert bad" style={{ marginTop: 16 }}>{error}</div>}<Link href="/" className="g-cta ghost" style={{ display: "block", textAlign: "center", textDecoration: "none", marginTop: 16 }}>Back to console</Link></div></main></div>;
}
